# Generated by Django 5.2 on 2026-03-09 05:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0003_provider_commission_type_provider_commission_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Amenity Name')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='Icon Name for Mobile App')),
            ],
        ),
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('description', models.TextField(blank=True, verbose_name='Branch Description')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Branch Phone Number')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('address', models.CharField(max_length=512, verbose_name='Full Address')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Map Coordinates')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='branches', to='gyms.gymamenity')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_branches', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/branches/images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Will be used as the cover image on the app.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gyms.gymbranch')),
            ],
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred/Resold')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code Identifier')),
                ('is_resold', models.BooleanField(default=False, help_text='Indicates if this subscription was sold to another user.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Check-in Time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gyms.gymbranch')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gyms.gymsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Plan Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration in Days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(related_name='available_plans', to='gyms.gymbranch')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_plans', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Feature Name')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='gyms.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='gyms.subscriptionplan'),
        ),
    ]
