# Generated by Django 5.2 on 2026-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_checkout_hours', models.PositiveIntegerField(default=2, help_text='How many hours before a visitor is automatically checked out.', verbose_name='Auto Checkout Duration (Hours)')),
            ],
            options={
                'verbose_name': 'Gym Global Setting',
                'verbose_name_plural': 'Gym Global Settings',
            },
        ),
    ]
