# Generated by Django 5.2 on 2026-03-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gymglobalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='branch_logo',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/branches/logos/', verbose_name='Branch Specific Logo'),
        ),
    ]
