# Generated by Django 5.2 on 2026-03-09 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gymbranch_branch_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Branch Image', 'verbose_name_plural': 'Branch Images'},
        ),
        migrations.RemoveField(
            model_name='branchimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='branchimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 9, 12, 48, 32, 86995, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gyms.gymbranch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='branchimage',
            name='image',
            field=models.ImageField(upload_to='gyms/branches/gallery/', verbose_name='Image'),
        ),
    ]
