# Generated by Django 5.2 on 2026-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_branchimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='city',
            field=models.CharField(default='riyadh', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
    ]
