# Generated by Django 5.2 on 2026-03-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gymbranch_city'),
        ('providers', '0003_provider_commission_type_provider_commission_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_reference', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_checkout_time', models.DateTimeField()),
                ('is_currently_inside', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='providers.provider')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
