# Generated by Django 5.2 on 2026-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gymattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Will be used as the cover image on the app.'),
        ),
    ]
