# Generated by Django 5.2 on 2026-03-16 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_branchimage_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='crowd_level_high',
            field=models.PositiveIntegerField(default=95, help_text='Percentage threshold for High crowd (e.g., 95)'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='crowd_level_low',
            field=models.PositiveIntegerField(default=30, help_text='Percentage threshold for Low crowd (e.g., 30)'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='crowd_level_medium',
            field=models.PositiveIntegerField(default=70, help_text='Percentage threshold for Medium crowd (e.g., 70)'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward Points'),
        ),
        migrations.CreateModel(
            name='GymReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gyms.gymbranch', verbose_name='Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Gym Review',
                'verbose_name_plural': 'Gym Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymBranchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gyms.gymbranch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Branch Schedule',
                'verbose_name_plural': 'Branch Schedules',
                'ordering': ['day'],
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
