# Generated by Django 5.2 on 2026-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_gymbranch_crowd_level_high_gymbranch_crowd_level_low_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='reward_points',
        ),
        migrations.AddField(
            model_name='gymglobalsetting',
            name='points_conversion_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='How many Riyals equal 1 reward point for Gyms. (e.g., 10 means 1 point for every 10 SAR).', max_digits=6, verbose_name='Points Conversion Rate (SAR)'),
        ),
    ]
