# Generated by Django 5.2 on 2026-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_remove_subscriptionplan_reward_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False, help_text='Check this to override the schedule and show the gym as closed immediately.', verbose_name='Temporarily Closed'),
        ),
    ]
