# Generated by Django 5.2 on 2026-03-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_gymbranch_is_temporarily_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sport Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='gymattendance',
            name='provider',
        ),
        migrations.AddField(
            model_name='gymattendance',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gyms.gymbranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='estimated_stay_duration',
            field=models.PositiveIntegerField(default=120, help_text='Average time a member spends in this branch.', verbose_name='Estimated Stay Duration (Minutes)'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='branches', to='gyms.gymsport'),
        ),
    ]
