# Generated by Django 5.2 on 2026-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_gymsport_remove_gymattendance_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymamenity',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/amenities/icons/', verbose_name='Amenity Icon Image'),
        ),
    ]
