# Generated by Django 5.2 on 2026-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_gymamenity_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymamenity',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='gymsport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/sports/images/', verbose_name='Sport Image'),
        ),
    ]
