# Generated by Django 5.2 on 2026-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0013_remove_gymamenity_icon_name_gymsport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='gender',
            field=models.CharField(choices=[('men', 'Men Only'), ('women', 'Women Only'), ('mixed', 'Mixed / Both')], default='mixed', max_length=10, verbose_name='Target Gender'),
        ),
    ]
