# Generated by Django 5.2 on 2026-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0014_gymbranch_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymamenity',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {"ar": "مسبح", "en": "Swimming Pool"}'),
        ),
        migrations.AddField(
            model_name='gymsport',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {"ar": "ملاكمة", "en": "Boxing"}'),
        ),
        migrations.AlterField(
            model_name='gymamenity',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/amenities/icons/'),
        ),
        migrations.AlterField(
            model_name='gymamenity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Default Name'),
        ),
        migrations.AlterField(
            model_name='gymsport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/sports/images/'),
        ),
        migrations.AlterField(
            model_name='gymsport',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Default Name'),
        ),
    ]
