# Generated by Django 5.2 on 2026-04-11 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_gymamenity_translations_gymsport_translations_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsubscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gym_subscription', to='payments.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended (Disputed)'), ('transferred', 'Transferred/Resold')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='GymSubscriptionDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Dispute Reason')),
                ('status', models.CharField(choices=[('open', 'Open (Pending Admin Review)'), ('resolved', 'Resolved (Reinstated)'), ('closed', 'Closed (Subscription Cancelled)')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='Admin Resolution Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(help_text='The Provider account that reported the issue.', on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='gyms.gymsubscription')),
            ],
            options={
                'verbose_name': 'Subscription Dispute',
                'verbose_name_plural': 'Subscription Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
