# Generated by Django 5.2 on 2026-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_gymsubscription_payment_alter_gymsubscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymbranch',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='gymbranch',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='JSON representation of flexible operating hours by day and gender.', verbose_name='Operating Hours'),
        ),
    ]
