# Generated by Django 5.2 on 2026-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_remove_gymbranch_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='plans', to='gyms.gymamenity'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='plans', to='gyms.gymsport'),
        ),
    ]
