# Generated by Django 5.2 on 2026-04-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0018_subscriptionplan_amenities_subscriptionplan_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived Status'),
        ),
    ]
