# Generated by Django 5.2 on 2026-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0019_subscriptionplan_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymglobalsetting',
            name='earnings_hold_days',
            field=models.PositiveIntegerField(default=3, help_text='Number of days before gym earnings become available for withdrawal.', verbose_name='Earnings Hold Period (Days)'),
        ),
    ]
