# Generated by Django 5.2 on 2026-04-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0020_gymglobalsetting_earnings_hold_days'),
        ('providers', '0003_provider_commission_type_provider_commission_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tier Name')),
                ('level', models.PositiveIntegerField(help_text='Higher integer means higher tier (e.g., 1=Basic, 4=VIP).', unique=True, verbose_name='Hierarchy Level')),
                ('description', models.TextField(blank=True, verbose_name='Tier Description')),
            ],
            options={
                'verbose_name': 'Gym Tier',
                'verbose_name_plural': 'Gym Tiers',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='is_roaming_enabled',
            field=models.BooleanField(default=False, help_text='Check to allow users from other gyms to visit this branch using points.', verbose_name='Enable Roaming'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='roaming_visit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fiat price for a single roaming visit. Converts to points dynamically.', max_digits=10, verbose_name='Roaming Visit Price (SAR)'),
        ),
        migrations.AddField(
            model_name='gymbranch',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='gyms.gymtier', verbose_name='Gym Classification Tier'),
        ),
        migrations.CreateModel(
            name='ProviderRoamingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_visits_balance', models.PositiveIntegerField(default=0, help_text='Available free visits to offset roaming entry costs.', verbose_name='Free Visits Balance')),
                ('total_earned_visits', models.PositiveIntegerField(default=0, verbose_name='Total Earned Visits')),
                ('total_consumed_visits', models.PositiveIntegerField(default=0, verbose_name='Total Consumed Visits')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roaming_pool', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Provider Roaming Pool',
                'verbose_name_plural': 'Provider Roaming Pools',
            },
        ),
    ]
