# Generated by Django 5.2 on 2026-04-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0021_gymtier_gymbranch_is_roaming_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranch',
            name='requested_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_branches', to='gyms.gymtier', verbose_name='Requested Tier (Pending Admin Approval)'),
        ),
        migrations.AddField(
            model_name='gymglobalsetting',
            name='roaming_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Percentage discount on the app's commission for branches that enable the roaming system.", max_digits=5, verbose_name='Roaming Commission Discount (%)'),
        ),
        migrations.AlterField(
            model_name='gymbranch',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_branches', to='gyms.gymtier', verbose_name='Approved Tier'),
        ),
    ]
