# Generated by Django 5.2 on 2026-04-26 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0022_gymbranch_requested_tier_and_more'),
        ('payments', '0002_paymentglobalsetting_providerwallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTierUpgrade',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Tier Request',
                'verbose_name_plural': 'Pending Tier Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gyms.gymbranch',),
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gyms.gymsubscription'),
        ),
        migrations.CreateModel(
            name='RoamingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField(default=0, verbose_name='Points Used')),
                ('fiat_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiat Paid')),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code Identifier')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roaming_passes', to='gyms.gymbranch')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roaming_pass', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roaming_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roaming Pass',
                'verbose_name_plural': 'Roaming Passes',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='roaming_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gyms.roamingpass'),
        ),
    ]
