# Generated by Django 5.2 on 2026-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0023_pendingtierupgrade_alter_gymvisit_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended (Disputed)'), ('transferred', 'Transferred/Resold')], default='active', max_length=20),
        ),
    ]
