# Generated by Django 5.2 on 2026-05-17 18:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0024_alter_gymsubscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Tag Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Default Label Name')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Format: {"ar": "أجهزة حديثة", "en": "Modern Equipment"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gym Review Tag',
                'verbose_name_plural': 'Gym Review Tags',
            },
        ),
        migrations.RemoveField(
            model_name='gymreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='gymreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='gymreview',
            name='cleanliness_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Cleanliness Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymreview',
            name='equipment_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Equipment Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymreview',
            name='review_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Review Commentary'),
        ),
        migrations.AddField(
            model_name='gymreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='gymreview',
            name='vibe_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Vibe Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymreview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='gyms.gymreviewtag', verbose_name='Micro Tags'),
        ),
        migrations.AddConstraint(
            model_name='gymreview',
            constraint=models.UniqueConstraint(fields=('branch', 'user'), name='unique_branch_user_review'),
        ),
    ]
