# Generated by Django 5.2 on 2026-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, help_text='Required for identity verification.', null=True, upload_to='users/verification/id_cards/', verbose_name='ID Card Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_face_image',
            field=models.ImageField(blank=True, help_text='Required for gym subscription check-ins.', null=True, upload_to='users/verification/faces/', verbose_name='Real Face Image'),
        ),
    ]
