# Generated by Django 5.2 on 2026-04-06 04:55

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userverificationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverificationtoken',
            options={'verbose_name': 'Verification Token', 'verbose_name_plural': 'Verification Tokens'},
        ),
        migrations.RemoveField(
            model_name='userverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='userverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=apps.users.models.get_otp_expiration),
        ),
        migrations.AddField(
            model_name='userverificationtoken',
            name='otp',
            field=models.CharField(default=apps.users.models.generate_otp, max_length=6, unique=True, verbose_name='One Time Password'),
        ),
        migrations.AlterField(
            model_name='userverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
