# Generated by Django 5.2 on 2026-04-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
