# Generated by Django 5.2 on 2026-05-10 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0023_pendingtierupgrade_alter_gymvisit_subscription_and_more'),
        ('payments', '0002_paymentglobalsetting_providerwallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='The percentage of the resale price the app takes as commission.', max_digits=5, verbose_name='App Commission (%)')),
                ('minimum_days_buffer', models.PositiveIntegerField(default=7, help_text='Subscriptions cannot be listed if the remaining days are less than this value.', verbose_name='Minimum Days Buffer')),
                ('escrow_hold_hours', models.PositiveIntegerField(default=24, help_text='How long the funds are held after purchase before being released to the seller.', verbose_name='Escrow Hold Duration (Hours)')),
            ],
            options={
                'verbose_name': 'Resale Global Setting',
                'verbose_name_plural': 'Resale Global Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionResaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='The price the seller is asking for. Must be <= fair value.', max_digits=10, verbose_name='Asking Price (SAR)')),
                ('fair_value_at_listing', models.DecimalField(decimal_places=2, help_text='System calculated pro-rata value when listed to prevent scalping.', max_digits=10, verbose_name='Fair Value at Listing')),
                ('status', models.CharField(choices=[('active', 'Active / Listed'), ('sold', 'Sold'), ('cancelled', 'Cancelled by Seller'), ('expired', 'Expired (Removed by System)')], default='active', max_length=20, verbose_name='Listing Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_listings', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resale_listing', to='gyms.gymsubscription', verbose_name='Original Subscription')),
            ],
            options={
                'verbose_name': 'Subscription Resale Listing',
                'verbose_name_plural': 'Subscription Resale Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final Sale Price')),
                ('app_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='App Commission')),
                ('seller_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Seller Earnings')),
                ('status', models.CharField(choices=[('escrow', 'In Escrow (Pending Clearance)'), ('completed', 'Completed (Funds Released)'), ('refunded', 'Disputed & Refunded')], default='escrow', max_length=20, verbose_name='Transaction Status')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='Funds Cleared At')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resale_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resale_transaction', to='payments.paymenttransaction', verbose_name='Payment Record')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='resale.subscriptionresalelisting', verbose_name='Resale Listing')),
            ],
            options={
                'verbose_name': 'Resale Transaction',
                'verbose_name_plural': 'Resale Transactions',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
