# Generated by Django 5.2 on 2026-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaleglobalsetting',
            name='depreciation_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='The immediate value reduction percentage applied to a subscription to prevent selling at the original purchase price.', max_digits=5, verbose_name='Immediate Depreciation (%)'),
        ),
    ]
