# Generated by Django 5.2 on 2026-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_version', models.FloatField(default=1.0, verbose_name='Sports Data Version')),
                ('amenities_version', models.FloatField(default=1.0, verbose_name='Amenities Data Version')),
                ('cities_version', models.FloatField(default=1.0, verbose_name='Cities Data Version')),
                ('android_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Android App Version')),
                ('ios_version', models.CharField(default='1.0.0', max_length=20, verbose_name='iOS App Version')),
                ('force_update', models.BooleanField(default=False, verbose_name='Force App Update')),
                ('update_message', models.TextField(blank=True, verbose_name='Update Message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configuration',
            },
        ),
    ]
