# Generated by Django 5.2 on 2026-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code (e.g., riyadh)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Default/Fallback name (e.g., Riyadh)', max_length=100)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Format: {"ar": "الرياض", "en": "Riyadh", "fr": "Riyad"}')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
