# Generated by Django 5.2 on 2026-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='service_types_version',
            field=models.FloatField(default=1.0, verbose_name='Service Types Version'),
        ),
    ]
