# Generated by Django 5.2 on 2026-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_lat_city_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='points_config_version',
            field=models.FloatField(default=1.0, verbose_name='Points Config Version'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='premium_points_required',
            field=models.PositiveIntegerField(default=1000, verbose_name='Premium Points Required'),
        ),
    ]
