# Generated by Django 5.2 on 2026-04-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appconfiguration_points_config_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='points_config_version',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='premium_points_required',
        ),
    ]
