# Generated by Django 5.2 on 2026-03-05 06:27

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('gym', 'Gym'), ('trainer', 'Trainer'), ('restaurant', 'Restaurant'), ('store', 'Store')], db_index=True, max_length=20, verbose_name='Provider type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('business_name', models.CharField(db_index=True, max_length=255, verbose_name='Business name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/logos/', verbose_name='Logo')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='City')),
                ('address', models.CharField(blank=True, default='', max_length=512, verbose_name='Address')),
                ('commercial_registration', models.CharField(blank=True, default='', max_length=100, verbose_name='Commercial registration number')),
                ('tax_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Tax ID number')),
                ('bank_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Bank name')),
                ('iban', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='IBAN')),
                ('bank_account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Bank account number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['-created_at'],
            },
        ),
    ]
