# Generated by Django 5.2 on 2026-03-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_add_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Commission Type'),
        ),
        migrations.AddField(
            model_name='provider',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Value'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/logos/', verbose_name='Business Logo'),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Commercial Register, Owner ID', max_length=255)),
                ('file', models.FileField(upload_to='providers/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.provider')),
            ],
        ),
    ]
