# Generated by Django 5.2 on 2026-04-23 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_earn_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Amount to spend in Gyms to earn 1 point.', max_digits=10, verbose_name='Gym Earn Rate (SAR per Point)')),
                ('trainer_earn_rate', models.DecimalField(decimal_places=2, default=40.0, help_text='Amount to spend with Trainers to earn 1 point.', max_digits=10, verbose_name='Trainer Earn Rate (SAR per Point)')),
                ('store_earn_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount to spend in Stores to earn 1 point.', max_digits=10, verbose_name='Store Earn Rate (SAR per Point)')),
                ('point_to_fiat_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='How many points equal 1 SAR when paying for roaming.', max_digits=10, verbose_name='Point to Fiat Rate (Points per SAR)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Global Setting',
                'verbose_name_plural': 'Loyalty Global Settings',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Milestone Title')),
                ('required_lifetime_points', models.PositiveIntegerField(help_text='The threshold to unlock this milestone (e.g., 10000).', unique=True, verbose_name='Required Lifetime Points')),
                ('reward_type', models.CharField(choices=[('free_roaming', 'Free Roaming Visit'), ('tier_upgrade', 'Tier Upgrade (Temporary)'), ('freeze_sub', 'Free Subscription Freeze'), ('roaming_pass', 'Open Roaming Pass')], max_length=30)),
                ('reward_value', models.PositiveIntegerField(help_text='Depends on reward type (e.g., 1 visit, 7 days upgrade, 30 days freeze).')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['required_lifetime_points'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiat_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Money from sold subscriptions or refunds.', max_digits=12, verbose_name='Fiat Balance (SAR)')),
                ('points_balance', models.PositiveIntegerField(default=0, help_text='Points available to spend on roaming or upgrades.', verbose_name='Spendable Points')),
                ('lifetime_points', models.PositiveIntegerField(default=0, help_text='Never decreases. Used for Milestone Roadmap progression.', verbose_name='Lifetime Points')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Wallet',
                'verbose_name_plural': 'Customer Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn_purchase', 'Earned from Purchase'), ('buy_points', 'Bought Points via Gateway'), ('spend_roaming', 'Spent on Roaming Visit'), ('sell_sub', 'Fiat Earned from Selling Sub'), ('withdraw_fiat', 'Fiat Withdrawal'), ('refund', 'Refunded')], max_length=30)),
                ('points_amount', models.IntegerField(default=0, help_text='Positive for earnings, negative for spending.')),
                ('fiat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Positive for deposits, negative for withdrawals.', max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerwallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='Reward Consumed')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_users', to='loyalty.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Milestone',
                'verbose_name_plural': 'User Milestones',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'milestone')},
            },
        ),
    ]
