# Generated by Django 5.2 on 2026-04-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('points', models.PositiveIntegerField(verbose_name='Points Amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (SAR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point Package',
                'verbose_name_plural': 'Point Packages',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_points_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum allowed discount using points when buying a regular subscription.', max_digits=5, verbose_name='Max Subscription Discount (%)'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='point_to_fiat_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='How many points equal 1 SAR when evaluating discounts or roaming.', max_digits=10, verbose_name='Point to Fiat Rate (Points per SAR)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn_purchase', 'Earned from Purchase'), ('buy_points', 'Bought Points via Gateway'), ('spend_roaming', 'Spent on Roaming Visit'), ('spend_discount', 'Spent on Subscription Discount'), ('sell_sub', 'Fiat Earned from Selling Sub'), ('withdraw_fiat', 'Fiat Withdrawal'), ('refund', 'Refunded')], max_length=30),
        ),
    ]
