# Generated by Django 5.2 on 2026-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_pointpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='roadmap_version',
            field=models.PositiveIntegerField(default=1, help_text='Increment this number whenever you change milestones. It forces the mobile app to fetch the new roadmap.', verbose_name='Roadmap Version'),
        ),
    ]
