# Generated by Django 5.2 on 2026-04-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_loyaltyglobalsetting_roadmap_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Free Protein Shake' or '1 Free Roaming Visit'", max_length=255)),
                ('action_type', models.CharField(choices=[('sys_roaming', 'System Action: Add Free Roaming Pass'), ('sys_extension', 'System Action: Extend Active Subscription'), ('manual', 'Manual Fulfillment (e.g. Free Item, Shirt, Shake)')], default='manual', max_length=50)),
                ('action_value', models.PositiveIntegerField(default=1, help_text='Value for system actions (e.g., 1 visit, 7 days). Ignored for manual.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Milestone Reward Definition',
                'verbose_name_plural': 'Milestone Reward Definitions',
            },
        ),
        migrations.RemoveField(
            model_name='loyaltyglobalsetting',
            name='max_points_discount_percent',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='reward_type',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='reward_value',
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_global_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum allowed discount using points for any purchase.', max_digits=5, verbose_name='Max Global Discount (%)'),
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='restaurant_earn_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Restaurant Earn Rate (SAR per Point)'),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='fiat_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Fiat Balance (SAR)'),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Lifetime Points'),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='points_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Spendable Points'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='gym_earn_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Gym Earn Rate (SAR per Point)'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='point_to_fiat_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Point to Fiat Rate (Points per SAR)'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='roadmap_version',
            field=models.PositiveIntegerField(default=1, help_text='Auto-increments when milestones or economic rates change.', verbose_name='Roadmap Version'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='store_earn_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Store Earn Rate (SAR per Point)'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='trainer_earn_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10, verbose_name='Trainer Earn Rate (SAR per Point)'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='required_lifetime_points',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usermilestone',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='points_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn_purchase', 'Earned from Purchase'), ('buy_points', 'Bought Points via Gateway'), ('spend_roaming', 'Spent on Roaming Visit'), ('spend_discount', 'Spent on Discount'), ('sell_sub', 'Fiat Earned from Selling Sub'), ('withdraw_fiat', 'Fiat Withdrawal'), ('refund', 'Refunded')], max_length=30),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='milestones', to='loyalty.milestonereward'),
        ),
    ]
