# Generated by Django 5.2 on 2026-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_milestonereward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermilestone',
            name='consumed_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
    ]
