# Generated by Django 5.2 on 2026-05-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_usermilestone_consumed_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonereward',
            name='action_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milestonereward',
            name='constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='milestonereward',
            name='fulfillment_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate / System Applied'), ('CONTEXTUAL', 'Contextual / Checkout'), ('QR_VERIFIED', 'In-Person / QR Scanned'), ('DELIVERY', 'Shipped / Delivered')], default='IMMEDIATE', max_length=20),
        ),
    ]
