# Generated by Django 5.2 on 2026-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_milestonereward_action_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermilestone',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
