# Generated by Django 5.2 on 2026-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_usermilestone_claimed_at_usermilestone_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonereward',
            name='action_type',
            field=models.CharField(choices=[('sys_roaming', 'System Action: Add Free Roaming Pass'), ('sys_extension', 'System Action: Extend Active Subscription'), ('gen_coupon', 'System Action: Generate Discount Coupon'), ('manual', 'Manual Fulfillment (e.g. Free Item, Shirt, Shake)')], default='manual', max_length=50),
        ),
    ]
