# Generated by Django 5.2 on 2026-05-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('loyalty', '0008_alter_milestonereward_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonereward',
            name='coupon_definition',
            field=models.ForeignKey(blank=True, help_text="Select a coupon template if Action Type is 'Generate Discount Coupon'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_rewards', to='coupons.coupondefinition', verbose_name='Coupon Template'),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='action_value',
            field=models.PositiveIntegerField(default=1, help_text='Value for system actions (e.g., 1 visit, 7 days). Ignored for manual or coupons.'),
        ),
    ]
