# Generated by Django 5.2 on 2026-05-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_milestonereward_coupon_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonereward',
            name='action_route',
        ),
        migrations.RemoveField(
            model_name='milestonereward',
            name='constraints',
        ),
    ]
