# Generated by Django 5.2 on 2026-05-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('loyalty', '0010_remove_milestonereward_action_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='max_global_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Max Global Discount (%)'),
        ),
        migrations.AlterField(
            model_name='loyaltyglobalsetting',
            name='roadmap_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Roadmap Version'),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='action_type',
            field=models.CharField(choices=[('sys_roaming', 'Free Roaming Visits'), ('sys_extension', 'Subscription Extension (Days)'), ('gen_coupon', 'Discount Coupon'), ('manual', 'Physical Gift (e.g. T-Shirt, Meal)')], default='gen_coupon', max_length=50),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='action_value',
            field=models.PositiveIntegerField(default=1, help_text='Ignore this field if you are creating a Discount Coupon.', verbose_name='Days / Visits Amount'),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='coupon_definition',
            field=models.ForeignKey(blank=True, help_text="Required ONLY if you selected 'Discount Coupon' above.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_rewards', to='coupons.coupondefinition', verbose_name='Coupon Template'),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Reward Name'),
        ),
    ]
