# Generated by Django 5.2 on 2026-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_alter_loyaltyglobalsetting_max_global_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermilestone',
            name='consumed_details',
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='reward_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reward Payload (QR/Coupon)'),
        ),
    ]
