# Generated by Django 5.2 on 2026-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_remove_usermilestone_consumed_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyglobalsetting',
            name='max_global_discount_percent',
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_discount_gym_plan',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Max Points Discount: Gym Plans (%)'),
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_discount_packages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Max Points Discount: Points Packages (%)'),
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_discount_resale',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Max Points Discount: Resale Market (%)'),
        ),
        migrations.AddField(
            model_name='loyaltyglobalsetting',
            name='max_discount_roaming',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Max Points Discount: Roaming (%)'),
        ),
    ]
