# Generated by Django 5.2 on 2026-05-16 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_remove_loyaltyglobalsetting_max_global_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonereward',
            name='coupon_definition',
        ),
        migrations.AddField(
            model_name='milestonereward',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20, null=True, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='milestonereward',
            name='action_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Granted Value'),
        ),
    ]
