# Generated by Django 5.2 on 2026-05-17 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0014_remove_milestonereward_coupon_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpackage',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Purchases'),
        ),
        migrations.AddField(
            model_name='pointpackage',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Revenue (SAR)'),
        ),
    ]
