# Generated by Django 5.2 on 2026-04-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('providers', '0003_provider_commission_type_provider_commission_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_hold_days', models.PositiveIntegerField(default=3, help_text='Number of days before provider earnings become available for withdrawal.', verbose_name='Earnings Hold Period (Days)')),
            ],
            options={
                'verbose_name': 'Payment Global Setting',
                'verbose_name_plural': 'Payment Global Settings',
            },
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pending Balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Available Balance')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Withdrawn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='providers.provider', verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earning_pending', 'Earning (Pending Clearance)'), ('earning_cleared', 'Earning (Cleared to Available)'), ('withdrawal_request', 'Withdrawal (Locked Funds)'), ('withdrawal_refund', 'Withdrawal Failed (Refunded)')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_cleared', models.BooleanField(db_index=True, default=False)),
                ('clearance_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.providerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('processing', 'Processing Bank Transfer'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
