# Generated by Django 5.2 on 2026-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentglobalsetting_providerwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentglobalsetting',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Global Value Added Tax applied to purchases.', max_digits=5, verbose_name='VAT Percentage (%)'),
        ),
    ]
