# Generated by Django 5.2 on 2026-05-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Internal Title')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('bogo', 'Buy One Get One (BOGO)'), ('sub_extension', 'Subscription Extension (Days)'), ('free_item', 'Free Specific Item')], max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Value based on type (e.g., 20 for 20%, or 50 for 50 SAR. Use 0 for Free Shipping/BOGO).', max_digits=10, verbose_name='Discount Value')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='How many days the coupon remains valid after being generated for a user.', verbose_name='Validity Duration (Days)')),
                ('rules_payload', models.JSONField(blank=True, default=dict, help_text="JSON format for extra flexibility. e.g., {'min_cart_value': 100, 'target_product_id': 5}", verbose_name='Dynamic Rules & Constraints')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon Definition',
                'verbose_name_plural': 'Coupon Definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Coupon Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_coupons', to='coupons.coupondefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Coupon',
                'verbose_name_plural': 'User Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
