# Generated by Django 5.2 on 2026-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondefinition',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed_amount', 'Fixed Amount Discount (SAR)'), ('free_shipping', 'Free Shipping'), ('bogo', 'Buy One Get One Free (BOGO)'), ('free_item', 'Free Specific Item')], max_length=50),
        ),
    ]
