# Generated by Django 5.2 on 2026-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupondefinition_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondefinition',
            name='source',
            field=models.CharField(choices=[('marketing', 'Marketing Campaign'), ('loyalty', 'Loyalty System Reward')], default='marketing', max_length=50, verbose_name='Coupon Source'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='fiat_discount_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiat Discount Applied (SAR)'),
        ),
    ]
