# Generated by Django 5.2 on 2026-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupondefinition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondefinition',
            name='code',
            field=models.CharField(blank=True, help_text='Required for Marketing campaigns. Leave blank for Loyalty.', max_length=50, null=True, unique=True, verbose_name='Public Coupon Code'),
        ),
        migrations.AddField(
            model_name='coupondefinition',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Campaign Expiration Date'),
        ),
        migrations.AddField(
            model_name='coupondefinition',
            name='max_usage',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited usage.', verbose_name='Maximum Total Usages'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
